### ISSUE TITLE
Any objection to moving the gtk2 requirement from 2.10 to 2.18?

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#118]
It would remove all of the GTK_CHECK_VERSION()s for 2.x, and many of the changes for GTK3 wouldn't require version checks because they were existing by 2.18, but the 2.x series still carried the functions that were replaced for compatibility. The compatibility was only removed in 3.0.
GTK+2.18 was released around September 2009.

After PR #125:
```
grep -nr --include='*.[hc]' "GTK_CHECK_VERSION(2" *
shell/report.c:805:#if GTK_CHECK_VERSION(2, 14, 0)
shell/report.c:896:#if GTK_CHECK_VERSION(2, 18, 0)
shell/report.c:907:#if GTK_CHECK_VERSION(2, 18, 0)
shell/report.c:915:#if GTK_CHECK_VERSION(2, 14, 0)
shell/report.c:933:#if GTK_CHECK_VERSION(2, 18, 0)
shell/report.c:943:#if GTK_CHECK_VERSION(2, 18, 0)
shell/shell.c:123:#if GTK_CHECK_VERSION(2,16,0)
shell/shell.c:515:#if GTK_CHECK_VERSION(2, 18, 0)
shell/shell.c:843:#if GTK_CHECK_VERSION(2, 14, 0)
shell/shell.c:862:#if GTK_CHECK_VERSION(2, 14, 0)
shell/shell.c:896:#if GTK_CHECK_VERSION(2, 14, 0)
shell/shell.c:952:#if GTK_CHECK_VERSION(2, 18, 0)
shell/shell.c:1001:#if GTK_CHECK_VERSION(2, 18, 0)
shell/shell.c:1017:#if GTK_CHECK_VERSION(2, 18, 0)
shell/shell.c:1401:#if GTK_CHECK_VERSION(2, 14, 0)
shell/shell.c:1409:#if GTK_CHECK_VERSION(2, 14, 0)
shell/shell.c:1464:#if GTK_CHECK_VERSION(2, 14, 0)
shell/shell.c:1475:#if GTK_CHECK_VERSION(2,12,0)
shell/shell.c:1963:#if GTK_CHECK_VERSION(2,12,0)
shell/syncmanager.c:670:#if GTK_CHECK_VERSION(2, 14, 0)
shell/syncmanager.c:739:#if GTK_CHECK_VERSION(2, 14, 0)
shell/syncmanager.c:752:#if GTK_CHECK_VERSION(2, 18, 0)
shell/syncmanager.c:761:#if GTK_CHECK_VERSION(2, 18, 0)
shell/syncmanager.c:771:#if GTK_CHECK_VERSION(2, 18, 0)
shell/callbacks.c:118:#if GTK_CHECK_VERSION(2, 12, 0)
shell/callbacks.c:189:#if GTK_CHECK_VERSION(2, 12, 0)
```

**Comment by lpereira** [comment]
I don't object at all. A library released 8 years ago is definitely not a
bleeeding edge version; if someone is still using it, they should really
consider updating.

**Comment by mckaygerhard** [comment]
i have a rude and clear pleany objection!!!!!

:-1:    :-1: :-1: 

doonttt i used hardinfo in many embebed projects.. and those linux cannot be too recents in software, due the problem its performance.. recent gtk 2.2o forces me to upgrade then Cairo, pango and some others like gtkmm due incompatibilities..

some of my software are navigations for tractors and GPR (ground penetration radars) (in experimental fase) , fiscal printers with own interfaces, all of them for countries of low economic or limited resources..  not all the people have spense hardware

**Comment by wdlkmpx** [comment]
People with very old/slow hardware are certainly using gtk 2.18+.. it was released even before ubuntu lucid

**Comment by mckaygerhard** [comment]
umm i have puppy linux in one of my DARUMA's.. but i can't remenber where..  come with great improved software for light desktop and environment, the LXpup have a very flat and single theme.. 

well in the daruma's we only have 512Mb of ram, there are machines for POS, i setup a pos system using gambas and linux, scanners bars and more, but linux cant be too recent performance are affected, in same way libraries..  those machines are working perfectly .. hardinfo its a important piece to retrieve info from those setups without expert usage..

**Comment by bp0** [comment]
The Raspberry Pi is less powerful than any of that. It has 256MB of RAM and a CPU "equivalent to a 300MHz Pentium II." Yet, Raspbian ships GTK+2.24, which is the latest and only supported version of GTK+2. GTK+2.24 was released in 2011.

**Comment by mckaygerhard** [comment]
the raspberry Pi has a less powerfull in hertz, but that's equivalent its not really true.. due its another arch..  the combination of hardware are enought powerfully, lest's compared the Asus EeePC 900 vs firs raspberry Pi, its clear that the performance of the asus are very down ...

but well the problem its for those that in compilation all the hardware combination does not have the power..  please dont let many users that can talk here out of the support

Many people do not have the intellect to be here writing something .. that does not mean that there is no voice .. I was thus a time that I did not have resources but I wanted to express myself.. now i can speak as those like have the same problem like me ..
