### ISSUE TITLE
Use JSON for benchmark.conf replacement

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#142]
More system information could be included and the results could be grouped by same machine. Something like simple [JSMN](http://zserge.com/jsmn.html) could be used to parse. Would probably make some future database sync easier as well.

After #141, could be something like:
```
{
  "board": < devices::getMotherboard >,
  "memory": < devices::getMemoryTotal >,
  "cpu_name": < devices::getProcessorName >,
  "cpu_desc": < devices::getProcessorDesc >,
  "cpu_config": < devices::getProcessorFrequencyDesc >,
  "results": {
         "CPU Zlib": 12.34,
         "FPU FFT": 78.91,
...
  }
}
```
Just an idea right now.

**Comment by lpereira** [comment]
JSON could be used, yeah, but I'd rather use another JSON library to parse. JSMN isn't a parser, it's a lexical scanner; maybe something like json-glib would be better.

The format should be changed as well; if the server ends up being online again, the results for a particular benchmark will most likely come from different devices.

**Comment by mckaygerhard** [comment]
its a great idea, inclusivelly usefully to inplement remote reports and communications.. 

but i think must finish some of the important task before starting with this, well i just my opinion..

**Comment by bp0** [comment]
In #147, I just extended the current benchmark.conf format. There is new code that will make using a different format easier in the future, but for now I am satisfied and will not try and implement JSON. I like the JSMN better because the GObject-based solution is bulky and, I think, overkill for this application.
