### ISSUE TITLE
hardinfo displays only the first HDD's temperature in Devices>Sensors

### ISSUE THREAD

**Issue by OldTango** [lpereira/hardinfo#15]
Hardinfo won't display all of my Hard Drive temps. It will only show the temp for my primary drive /dev/sda but not any additional drives. I have hddtemp installed and running. I have manually added my drives to /usr/share/hddtemp/hddtemp.db. I have editd /etc/conf.d/hddtemp to include checking of all my drives.

Drives installed
"WDC WD5000HHTZ-04N21V0"  194 C "Western Digital VelociRaptor 500GB" /dev/sda
"TOSHIBA DT01ACA300"      194 C "Toshiba 3TB" /dev/sbb
"Hitachi HDS723015BLA642" 194 C "Hitachi Deskstar 1.5TB" /dev/sdc
"HDT722516DLA380"         194 C "Hitachi Deskstar 160GB" /dev/sdd

I can manually run hddtemp on any /dev/? and it reports the current temp, but hardinfo doesn't appear to pick them up or display them in Devices>Sensors

**Comment by mckaygerhard** [comment]
@lpereira the output of telnet seems incorrect for spliting in code, only has split by "|" and then by "\n" ar the for.. but there's no new line char in the daemon out, so separator can be two options:
1) a double pipe "||" as can see each disk las work are "c" and then a double pipe
2) the word "/dev/" including bars

output of telnet in a large scale production server:

```
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
|/dev/sg0|MB0500EBZQA|32|C||/dev/sg1|MB0500EBZQA|32|C||/dev/sg2|TOSHIBA DT01ACA200|32|C||/dev/sg3|TOSHIBA DT01ACA200|32|C||/dev/sda|MB0500EBZQA|SLP|*||/dev/sdb|MB0500EBZQA|SLP|*||/dev/sdc|TOSHIBA DT01ACA200|32|C||/dev/sdd|TOSHIBA DT01ACA200|32|C|Connection closed by foreign host.
```

i'll try some piece of code and then paste here even made a pull request after u reviewed

**Comment by kmikita** [comment]
Fix it and correct unit show.
````
---
 modules/devices/sensors.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/modules/devices/sensors.c b/modules/devices/sensors.c
index 696bc2d..8bcc783 100644
--- a/modules/devices/sensors.c
+++ b/modules/devices/sensors.c
@@ -525,7 +525,7 @@ static void read_sensors_hddtemp(void) {
         gchar **disks;
         int i;
 
-        disks = g_strsplit(buffer, "\n", 0);
+        disks = g_strsplit(buffer, "||", 0);
         for (i = 0; disks[i]; i++) {
             gchar **fields = g_strsplit(disks[i] + 1, "|", 5);
 
@@ -536,7 +536,7 @@ static void read_sensors_hddtemp(void) {
              * 3 -> C
              */
             const gchar *unit = strcmp(fields[3], "C")
-                ? "\302\260C" : "\302\260F";
+                ? "\302\260F" : "\302\260C";
             add_sensor("Drive Temperature",
                        fields[1],
                        "hddtemp",
-- 
2.17.1
````

**Comment by lpereira** [comment]
Thanks for the patch, @kmikita!  If you send it in a PR, I can merge it and properly credit you.
