### ISSUE TITLE
Crash (GTK3 build)

### ISSUE THREAD

**Issue by TotalCaesar659** [lpereira/hardinfo#150]
After compiling latest master build with GTK3, it crashes after pressing "Summary" with output:
>hardinfo: symbol lookup error: /usr/lib/hardinfo/modules/computer.so: undefined symbol: info_new

GTK2 version is OK (as GTK3 version before).

**Comment by bp0** [comment]
Thanks for testing. Should be fixed by #152.

**Comment by TotalCaesar659** [comment]
Yeah, it's fixed, thanks.
