### ISSUE TITLE
bug: translated report inconsistences

### ISSUE THREAD

**Issue by mckaygerhard** [lpereira/hardinfo#155]
i have a rusian desktop with spanish default locate.. and when i generated the hardinfo report from russian desktop the result are all in spanish and dont have any russian info.. i mean in the locate section said that only spanish are set and no english or/and russian are present.. but its!

Seems that if not all the LC_XXXXX variables are set will have a influence in the report as my env string reports for locale vars:

![hardinfo-russian-spanish-problem1](https://user-images.githubusercontent.com/1571724/29318808-955697f4-819f-11e7-9f69-ad7e866a82f9.png)

[hardinfo_report.txt](https://github.com/lpereira/hardinfo/files/1225215/hardinfo_report.txt)

**Comment by mckaygerhard** [comment]
soory wrong file name..  report are generated correctly in russian, but this are still pretty rare..

**if a russian person want to share info to another that does not know russian.. how the tecnician could read the file?**

attached the file corrected:
[hardinfo_report.txt](https://github.com/lpereira/hardinfo/files/1225237/hardinfo_report.txt)

**Comment by bp0** [comment]
I tried with `LANGUAGE=ru:es hardinfo` and I got the expected `Russian / fall-back to Spanish / fall-back to English` behavior. I'm not sure what can be done about how the system reports locale information to hardinfo.

**Comment by mckaygerhard** [comment]
umm yeah sound complicated, a frien of me tell me "i cant read" so me as overall user of linux made langauje change a send the report in english, but for normal users that command seems pretty complicated (O.o yeah as you can read, winbuntu and similars)... and he suggested me a "menu entry to generate in other lang" (As if it were that easy, 3 clicks and that's all)

well close it this issue!
