### ISSUE TITLE
Reversed polarity for progress bars

### ISSUE THREAD

**Issue by silv3rm00n** [lpereira/hardinfo#16]
The progress bar indicator is reversed

Here is a screenshot
http://s4.postimg.org/o19x16p65/kde_polarity.png

**Comment by bp0** [comment]
The looks, to me, like it was fixed.

**Comment by mckaygerhard** [comment]
gnome-puach fixed only: works in mate, gnome-puach, cinnamon, but         in lxde, kde or oopenbox dont

**Comment by lpereira** [comment]
Indeed, this has been fixed: the whole progress bar code has been rewritten, and even percentages should be consistent now.

Now, I find it curious it's not working on LXDE, KDE, or Openbox. Can you confirm you're running a recent enough version (newer than August 2016)? Is this possibly a theme issue?

**Comment by mckaygerhard** [comment]
was compiled the same day that i posted the comment, with debian 8.1 and Devuan too

**Comment by bp0** [comment]
The polarity is reversed after running a benchmark. I think the benchmark results view must be using the same GTK resources as the filesystem view, and they aren't properly reset when returning to Filesystems.
As far as I can tell, it behaves the same without regard to Desktop Environment, but I've only tested in XFCE, LXDE and KDE. I'd bet that GNOME is the same.

**Comment by mckaygerhard** [comment]
hey! when i paste the snapshot no benchmark was run! i go directly to the filesystem module!

**Comment by mckaygerhard** [comment]
i have enought desktop environment to test it! dont worry about that, but 
hey! when i paste the snapshot no benchmark was run! i go directly to the filesystem module!

**Comment by bp0** [comment]
* Comments can be edited, in case you weren't aware of that. 
* Please provide some details about the tested systems. I've just tested on up-to-date raspbian (lxde-openbox), kde neon, xubuntu, and all gave the behavior I described.

**Comment by mckaygerhard** [comment]
all the tested system are in my house and in my work, at my house a DELL inspiron 15R with Devuan, Xfce4 (i dont like that desktop, i just was installe and i not have time), Jeesie with linux 4.9, GTK 2.24.25 (+/-) and no KDE installed, never run the benchmark here..

at the work, the others, DELL T110-II, HP compat presario C700, those with LXDE 0.5.5 and Debian squeeze (due are very more faster rather recents) and kernel "3.2.<something>" using lasted hardinfo (git from yesterday now), with GTK 2.20.2 and Glib 2.25.X , some of these machines have Mate 1.6 and one have Debian 8.1 with recent Mate (i dont remenber version)
on those the benchmark was run before test the filesystem.. 

**NOW TAKE CARE OF THAT**: i restart the machine with Debian 8, start in clean Openbox desktop, run inmediatelly hardinfo compiled yesterday, goes directly to the filesystem **and the firs 20 seconds display info in good , but after 20 seconds some of the filesystems/lines goes to reverse!**

also an asus Eeepc with Debian etch (quite old but faster) with GTK 2.18.8 and kernel 2.6.34, using hardinfo 0.5.2-pre from May 2017

one machine have a virtualbox with suse, but i dischar due the libc6 problem was solved..

**Comment by mckaygerhard** [comment]
hey "shoud fix" are not  same as "fixed"... at least wait for tests!
seems fixed but i not at my work so i cannot test in lxde, openbox, was tested in Xfce and mate and seems in that desktops works now!

**Comment by bp0** [comment]
@lpereira 
I can still make the behavior I described earlier happen.
After running any benchmark, except CryptoHash, the filesystems view will be messed up. If selecting CryptoHash and then going back to filesystems, it will be ok again, even if it was messed up before. Select any other benchmark, and it will be messed up again, but CryptoHash will always reset it.

**Comment by mckaygerhard** [comment]
i can confirm that described by @bp0 as i posted, now in the morning i go to the work and tested again in openbox, but certanly after running some benchmarks.. the problem still happened
