### ISSUE TITLE
Support kFreeBSD/BSD

### ISSUE THREAD

**Issue by tsimonq2** [lpereira/hardinfo#166]
Debian (but not Ubuntu) builds packages for the kFreeBSD port, and so we should support building on that port (just amd64 and i386 for that port). *BSD support could also be accomplished in this patch.

**Comment by lpereira** [comment]
HardInfo relies heavily on Linux-only APIs (files from pseudo-filesystems such as /sys and /proc), which are either different (/proc, for instance) or non-existent (/sys).  Porting it to FreeBSD would be very time consuming.  While I wouldn't object to a patch series porting HardInfo to kFreeBSD, the code is already messy as it is, so I wouldn't hold my breath for something like this.

I'd just mask HardInfo on Debian so it's not built for kFreeBSD.  I believe that's the case now, right?

**Comment by tsimonq2** [comment]
Alright, sure.

Right now it builds on kfreebsd-* but I can disable that.

Thanks!
