### ISSUE TITLE
Update server not available - is the project dead?

### ISSUE THREAD

**Issue by strelec** [lpereira/hardinfo#18]
When I try to update the database, I get the following message:

```
Failed while performing "Contacting HardInfo Central Database". Please file a bug report if this problem persists. (Use the Help→Report bug option.)

Details: Could not parse XML-RPC response
```

If I try to report a bug, I get redirected to http://www.berlios.de/.

**Comment by Cediddi** [comment]
Hi, After 1 year, is there any way you can create a new database with a new hosting service. I bet someone can sponsor you, (or can we help).

**Comment by lpereira** [comment]
One problem is that older versions of HardInfo hardcoded the URL to `http://hardinfo.berlios.de`, so older versions wouldn't work with the new instance of the services.

I could try convincing the current Berlios owners to create a `CNAME` from `hardinfo.berlios.de` to my own domain, though. Money to run the service is not a problem; it's actually just cached a database query so it's pretty lightweight, and I can easily spare some space on machines I already have running 24/7.

The major problem, though, is that I'm not really using or developing HardInfo anymore, and so far nobody has stepped up to maintain it. So I'm not really sure if it's worth the effort as I have many other side projects now.

**Comment by Testato** [comment]
there is nothing like HardInfo on Gnu/Linux world.
I hope that some people continue your work.
Thanks for hardinfo
