### ISSUE TITLE
feature: please added info of current display number at screen section

### ISSUE THREAD

**Issue by mckaygerhard** [lpereira/hardinfo#181]
in module computer at screen section all the xorg info are show.. but the only info missing are the most important: the active number of screen.. 

today i try to lauch `Xephyr :1 -ac -screen 900x700 &` and to do i go to my "great hardinfo compilation" and then click on module and ummm what? no screen info are showed!

**Comment by bp0** [comment]
#199 adds the X Display Name to Computer/Display. There is, of course, DISPLAY in environment variables. Is this what you wanted?

**Comment by mckaygerhard** [comment]
hi @bp0 , of course hardinfo wil be run from a desktop environment so let's assumed that DISPLAY environment must be valid and set

very rare cases of limited desktop that are not set, but i cannot remenber right now. so i thinks are good.. please merge
