### ISSUE TITLE
HardInfo doesn't compile

### ISSUE THREAD

**Issue by TotalCaesar659** [lpereira/hardinfo#188]
After some recent PRs, HardInfo doesn't compile and shows this:

> [ 13%] Building C object CMakeFiles/devices.dir/modules/devices/devicetree.c.o
> In file included from /home/max/hardinfo/includes/x86/processor-platform.h:22:0,
>                  from /home/max/hardinfo/includes/devices.h:5,
>                  from /home/max/hardinfo/modules/devices/devicetree.c:28:
> /home/max/hardinfo/modules/devices/devicetree.c: In function ‘get_summary’:
> /home/max/hardinfo/modules/devices/devicetree.c:200:19: error: ‘tmp’ undeclared (first use in this function)
>          EMPIFNULL(tmp[0]);
>                    ^
> /home/max/hardinfo/includes/cpu_util.h:10:29: note: in definition of macro ‘STRIFNULL’
>  #define STRIFNULL(f,cs) if (f == NULL) f = g_strdup(cs);
>                              ^
> /home/max/hardinfo/modules/devices/devicetree.c:200:9: note: in expansion of macro ‘EMPIFNULL’
>          EMPIFNULL(tmp[0]);
>          ^
> /home/max/hardinfo/modules/devices/devicetree.c:200:19: note: each undeclared identifier is reported only once for each function it appears in
>          EMPIFNULL(tmp[0]);
>                    ^
> /home/max/hardinfo/includes/cpu_util.h:10:29: note: in definition of macro ‘STRIFNULL’
>  #define STRIFNULL(f,cs) if (f == NULL) f = g_strdup(cs);
>                              ^
> /home/max/hardinfo/modules/devices/devicetree.c:200:9: note: in expansion of macro ‘EMPIFNULL’
>          EMPIFNULL(tmp[0]);
>          ^
> /home/max/hardinfo/modules/devices/devicetree.c: In function ‘add_keys’:
> /home/max/hardinfo/modules/devices/devicetree.c:243:23: warning: passing argument 1 of ‘get_node’ from incompatible pointer type [-Wincompatible-pointer-types]
>      n_info = get_node(dt_path);
>                        ^
> /home/max/hardinfo/modules/devices/devicetree.c:41:15: note: expected ‘dtr * {aka struct _dtr *}’ but argument is of type ‘gchar * {aka char *}’
>  static gchar *get_node(dtr *dt, char *np) {
>                ^
> /home/max/hardinfo/modules/devices/devicetree.c:243:14: error: too few arguments to function ‘get_node’
>      n_info = get_node(dt_path);
>               ^
> /home/max/hardinfo/modules/devices/devicetree.c:41:15: note: declared here
>  static gchar *get_node(dtr *dt, char *np) {
>                ^
> /home/max/hardinfo/modules/devices/devicetree.c:256:26: warning: passing argument 1 of ‘add_keys’ from incompatible pointer type [-Wincompatible-pointer-types]
>                  add_keys(ntmp);
>                           ^
> /home/max/hardinfo/modules/devices/devicetree.c:232:13: note: expected ‘dtr * {aka struct _dtr *}’ but argument is of type ‘gchar * {aka char *}’
>  static void add_keys(dtr *dt, char *np) {
>              ^
> /home/max/hardinfo/modules/devices/devicetree.c:256:17: error: too few arguments to function ‘add_keys’
>                  add_keys(ntmp);
>                  ^
> /home/max/hardinfo/modules/devices/devicetree.c:232:13: note: declared here
>  static void add_keys(dtr *dt, char *np) {
>              ^
> /home/max/hardinfo/modules/devices/devicetree.c: In function ‘__scan_dtree’:
> /home/max/hardinfo/modules/devices/devicetree.c:296:18: warning: passing argument 1 of ‘add_keys’ from incompatible pointer type [-Wincompatible-pointer-types]
>          add_keys("/");
>                   ^
> /home/max/hardinfo/modules/devices/devicetree.c:232:13: note: expected ‘dtr * {aka struct _dtr *}’ but argument is of type ‘char *’
>  static void add_keys(dtr *dt, char *np) {
>              ^
> /home/max/hardinfo/modules/devices/devicetree.c:296:9: error: too few arguments to function ‘add_keys’
>          add_keys("/");
>          ^
> /home/max/hardinfo/modules/devices/devicetree.c:232:13: note: declared here
>  static void add_keys(dtr *dt, char *np) {
>              ^
> CMakeFiles/devices.dir/build.make:182: ошибка выполнения рецепта для цели «CMakeFiles/devices.dir/modules/devices/devicetree.c.o»
> make[2]: *** [CMakeFiles/devices.dir/modules/devices/devicetree.c.o] Ошибка 1
> CMakeFiles/Makefile2:104: ошибка выполнения рецепта для цели «CMakeFiles/devices.dir/all»
> make[1]: *** [CMakeFiles/devices.dir/all] Ошибка 2
> Makefile:127: ошибка выполнения рецепта для цели «all»
> make: *** [all] Ошибка 2
>

**Comment by bp0** [comment]
The culprit is 8913af3e0fb372e7df705015840166ec1b841043.
I don't see that so much is gained by conditionally compiling the rpi and power mac functions. There's nothing about them that can't work if not running rpi or powermac, and it prevents running on x86 while using the test cpuinfo from rpi, for example.

**Comment by lpereira** [comment]
I completely forgot about the testing infrastructure. Yeah, conditionally compiling those will thwart it. Will revert the #ifdefs.
