### ISSUE TITLE
[from Ubuntu] hardinfo -r from comand line always shows displays in X as 0x0 pixels

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#200]
https://bugs.launchpad.net/ubuntu/+source/hardinfo/+bug/1494523

Brendan Perrine:
> I expected hardinfo to show the display resolution like it does in a gtk window when run on the command line. Instead it shows 0x0 pixels no matter the display resolutoin. Instead I get 0x0 pixel from a terminal emulator and get the correct resolution in a gtk window.

This happens because the resolution information is from GDK, but that stuff hasn't been initialized. Also, the method used has been deprecated in GNOME, so it should be replaced anyway.

**Comment by tsimonq2** [comment]
Bump.

**Comment by bp0** [comment]
This is fixed as part of #237.
