### ISSUE TITLE
Bios version

### ISSUE THREAD

**Issue by Hub-29** [lpereira/hardinfo#215]
Hi , Hardinfo doesn't show the bios version number, but the name of the computer instead of

**Comment by bp0** [comment]
Can you attach a screen shot? What is the result of `sudo dmidecode -s bios-version`?

**Comment by Hub-29** [comment]
Sorry I'm wrong. I'm using an Asus computer and in the bios Asus give an exotic bios name instead of the real American Megatrends name and vers. Sorry for spending time ! Have a good day
