### ISSUE TITLE
Segmentation fault [generating HTML report]

### ISSUE THREAD

**Issue by Polesz** [lpereira/hardinfo#217]
Click generate report, choose filename and run, but

> 
Thread 1 "hardinfo" received signal SIGSEGV, Segmentation fault.
0x00007ffff4c2b036 in __strlen_sse2 () from /lib64/libc.so.6
>

**Comment by lpereira** [comment]
Thanks for the bug report -- are you seeing it with which version? 0.5.1, or something recently built from the current HEAD?

**Comment by Polesz** [comment]
Current HEAD version. OS: Slackware 14.2 (current)

**Comment by bp0** [comment]
Confirmed. The fix from 96980fbf494d9c453c6b558967c90c55e41abe2d needs to be applied to the html  version of that function.
