### ISSUE TITLE
lsusb from usbutils currently required for usb information

### ISSUE THREAD

**Issue by mckaygerhard** [lpereira/hardinfo#226]
the hardware are a MSI motherboard intel chipset G33, the usb info tree are not showed, module shows empty

-Product-
Nombre		: G31-M7 TE
Familia		: (Not available; Perhaps try running HardInfo as root.)
Proveedor		: BIOSTAR Group (SEAGATE, www.seagate.com)
Versión		: (Not available; Perhaps try running HardInfo as root.)
-BIOS-
Date		: 09/25/2009
Proveedor		: American Megatrends Inc. (American Megatrends, www.ami.com)
Versión		: 080014
-Tarjeta-
Nombre		: G31-M7 TE
Proveedor		: BIOSTAR Group (SEAGATE, www.seagate.com)
Versión		: (Not available; Perhaps try running HardInfo as root.)
Numero serial		: (Not available; Perhaps try running HardInfo as root.)
Asset Tag		: To Be Filled By O.E.M.
-Chassis-
Proveedor		: BIOSTAR Group (SEAGATE, www.seagate.com)
Tipo		: [3] PC Escritorio
Versión		: (Not available; Perhaps try running HardInfo as root.)
Numero serial		: (Not available; Perhaps try running HardInfo as root.)
Asset Tag		: None

**Comment by bp0** [comment]
What is the result of `lsusb`?

**Comment by mckaygerhard** [comment]
aarrggg hardwaree are gone for a while, but lsusb gives me right results in that moment: (umm how stupid i was, why not paste it), but i reviewed the pull and in my ignorance i already know about the "Check usage of popen() for leaks via stderr" so maybe it work, i'll go to the depot these days near and will test again

umm @bp0  for future issues will need a tools that gatering all the relevant info to contrast! may i suggest open a new task URGENT or proposes a templae, today i'll send a pull request EDITABLE about it (i mean that you cant manage and made commits agains)

**Comment by mckaygerhard** [comment]
now hardware got back, testing:

tested with lasted patch included not work, taking in consideration that PR #178 are now merged!

found the problem missing usbutils runtime depends, make pull request for information.

**Comment by bp0** [comment]
See #243.
