### ISSUE TITLE
Default location for libc.so.6

### ISSUE THREAD

**Issue by anlar** [lpereira/hardinfo#23]
There is a hardcoded path to that file: [/lib/libc.so.6](https://github.com/lpereira/hardinfo/blob/4f89b7e8cc4419d4916199ddb6e1b8c5c7910d05/modules/computer/os.c#L32) , but now in many distributions it's located in /usr/lib{64}/libc.so.6

See also:
- https://bugs.launchpad.net/ubuntu/+source/hardinfo/+bug/1307616
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=723858

**Comment by mckaygerhard** [comment]
a trick to this can be a option to predefined path, that when run cmake define a macro with location...

**Comment by mckaygerhard** [comment]
the libc6 issue path its solved in/since commit 6dd14fed6db519a2feb77a5b2b6e73ff03c4d043 are not longer applicable so please this solved and close this!

**Comment by tsimonq2** [comment]
In Ubuntu, I believe we still had this issue, and this patch is how we solved it:

```
--- a/modules/computer/os.c
+++ b/modules/computer/os.c
@@ -27,8 +27,7 @@ get_libc_version(void)
     FILE *libc;
     gchar buf[256], *tmp, *p;
     char *libc_paths[] = {
-		"/lib/ld-uClibc.so.0", "/lib64/ld-uClibc.so.0",
-		"/lib/libc.so.6", "/lib64/libc.so.6"
+		"ldconfig -V"
 	};
 	int i;
 	
@@ -47,15 +46,13 @@ get_libc_version(void)
     (void)fgets(buf, 256, libc);
     if (pclose(libc)) goto err;
 
-    tmp = strstr(buf, "version ");
-    if (!tmp) goto err;
+    buf[strlen(buf) - 1] = '\0';
 
-    p = strchr(tmp, ',');
-    if (p) *p = '\0';
-    else goto err;
+    tmp = strstr(buf, " ");
+    if (!tmp) goto err;
 
     return g_strdup_printf(_("GNU C Library version %s (%sstable)"),
-                           strchr(tmp, ' ') + 1,
+                           tmp + 1,
                            strstr(buf, " stable ") ? "" : _("un"));
   err:
     return g_strdup(_("Unknown"));
```

Is this something upstream (you guys) would accept?

**Comment by bp0** [comment]
This is recently fixed.

**Comment by mckaygerhard** [comment]
many other issues seem also fixed.. where lpereira have time, will close (i guess)
