### ISSUE TITLE
Errors reported command line on Summary

### ISSUE THREAD

**Issue by PanderMusubi** [lpereira/hardinfo#25]
On command line the following errors are reported when choosing Summary in HardInfo:

```
sh: 1: /lib/libc.so.6: not found
sh: 1: gnome-about: not found
```

The first is unclear why this is required, since Ubuntu doesn't ship that file, see http://packages.ubuntu.com/search?searchon=contents&keywords=libc.so.6&mode=exactfilename&suite=wily&arch=any

The second is also unclear why this is required as it is not available, see

```
apt-cache search gnome about|grep -i about
apt-cache search gnome-about|grep -i about
```

as both do not result in any package. This concerns HardInfo version 0.5.1 on Ubuntu 15.10 Wily.

**Comment by mckaygerhard** [comment]
seems your hardinfo are very old.. but lest search a bit

the firts error are due the glibc library on ur system are not in xpected place, seems like due winbutnu are follow debian root, libraries are in a M(Arch)-depend path due the new multiarch behavior that debian implements at the wheeze release!

the second error itws due the hardinfo are assuming and old desktop.. and its not a real error, its only for consult what version of gnomepuach are installed if gnomepuach are using, so if found, u'r desktop are gnomepuach

in last, all errors are related to ur system winbuntu

**Comment by bp0** [comment]
There are still leaks in some places. The fix is to use `g_spawn_command_line_sync()` instead of `popen()` and capture stderr so that it doesn't leak.

**Comment by mckaygerhard** [comment]
g_spawn_command_line_sync() its version check safe...  for glibc

**Comment by bp0** [comment]
Closing this issue about a singular instance of the problem, subscribe to #162 if to track progress.
