### ISSUE TITLE
compile error: missing include endian depending of unix flavor

### ISSUE THREAD

**Issue by mckaygerhard** [lpereira/hardinfo#253]
i got error when compiling in some systems, mostly BSD related and some older linuxes:

``` 
.0 -lgmodule-2.0 -lrt -lglib-2.0 -lz -lX11 
CMakeFiles/hardinfo.dir/hardinfo/dt_util.c.o: In function `dtr_elem_uint':
/debiandat/debianwork/hardinfo/hardinfo-0.6.0/hardinfo/dt_util.c:559: undefined reference to `be32toh'
CMakeFiles/hardinfo.dir/hardinfo/dt_util.c.o: In function `dtr_elem_hex':
/debiandat/debianwork/hardinfo/hardinfo-0.6.0/hardinfo/dt_util.c:551: undefined reference to `be32toh'
CMakeFiles/hardinfo.dir/hardinfo/dt_util.c.o: In function `dtr_elem_phref':
/debiandat/debianwork/hardinfo/hardinfo-0.6.0/hardinfo/dt_util.c:531: undefined reference to `be32toh'
/debiandat/debianwork/hardinfo/hardinfo-0.6.0/hardinfo/dt_util.c:542: undefined reference to `be32toh'
CMakeFiles/hardinfo.dir/hardinfo/dt_util.c.o: In function `dtr_list_hex':
/debiandat/debianwork/hardinfo/hardinfo-0.6.0/hardinfo/dt_util.c:590: undefined reference to `be32toh'
CMakeFiles/hardinfo.dir/hardinfo/dt_util.c.o:/debiandat/debianwork/hardinfo/hardinfo-0.6.0/hardinfo/dt_util.c:960: more undefined references to `be32toh' follow
```
seems we ned a patch but i not make a pull for that due i'm not sure how, i must some like:
so then help some here @lpereira and @bp0 :

```
#if defined(__linux__) // i dont know ho to detect in hardinfo how do you config @bpo ?
#include <endian.h> //htobe64,be64toh
#elif defined(__FreeBSD__) || defined(__NetBSD__) // ??? how to define swicht here?
#include <sys/endian.h>
#elif defined(__OpenBSD__)  // i dont know ho to detect in hardinfo how do you config @bpo ?
#define be16toh(x) betoh16(x)
#define be32toh(x) betoh32(x)
#define be64toh(x) betoh64(x)
#endif
```

**Comment by bp0** [comment]
Hardinfo uses Linux-speicific stuff that may or may not work in BSD. BSD isn't really supported.

**Comment by mckaygerhard** [comment]
hyeeyy, clam down it not only in BSD, also in my older "franskenteins" give me those errors, 
i'll try to make a patch but i dont understant , cmake already pass to the compiler gnu std 98 and the include are already there..

but also in all my linux have that error at compile time!

**Comment by mckaygerhard** [comment]
hyeeyy, clam down your horses! @bp0 , it not only in BSD, also in my older "franskenteins" give me those errors, 
i'll try to make a patch but i dont understant , cmake already pass to the compiler gnu std 98 and the include are already there..

but also in all my linux have that error at compile time!

**Comment by mckaygerhard** [comment]
im using gcc 4.9 debian jessie enought recent and still get errors! linux only!

i check and with ollder gcc ares same, already passed -std=gnu89 as cmake yet defined!

**Comment by bp0** [comment]
What does `man 3 endian` say on that system?
