### ISSUE TITLE
Uber-graph module can't be initialized

### ISSUE THREAD

**Issue by TotalCaesar659** [lpereira/hardinfo#261]
When building hardinfo with GTK3, the uber-graph module can't be initialized:
```
1@device:~/hardinfo$ git submodule update --init
Submodule 'deps/uber-graph' (https://github.com/chergert/uber-graph.git) registered for path 'deps/uber-graph'
Cloning into '/home/max/hardinfo/deps/uber-graph'...
Username for 'https://github.com': TotalCaesar659
Password for 'https://TotalCaesar659@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/chergert/uber-graph.git/' not found
fatal: clone of 'https://github.com/chergert/uber-graph.git' into submodule path '/home/1/hardinfo/deps/uber-graph' failed
Failed to clone 'deps/uber-graph'. Retry scheduled
Cloning into '/home/1/hardinfo/deps/uber-graph'...
Username for 'https://github.com': 
```
The repo has been moved to https://gitlab.gnome.org/chergert/uber-graph. @lpereira, @bp0, could you fix it?

**Comment by mckaygerhard** [comment]
submodule must be change the remote address at `https://github.com/lpereira/hardinfo/blob/master/.gitmodules` you can doit manually before initialization

umm i also suggested too that maybe we must move to gilab ! now github its a M$ crap!

**Comment by lpereira** [comment]
Fixed, thanks for noticing.

I'll continue using GitHub.  I have nothing against Microsoft.

**Comment by mckaygerhard** [comment]
seems the mayority are moving away! due obviously reasosn!

**Comment by lpereira** [comment]
Let them move. The good thing is that Git itself is distributed, they can go anywhere they please.  I'm fine on GitHub, it being owned privately, or by Microsoft. Anyway, this discussion is off-topic.  The issue reported by @TotalCaesar659 has been fixed, there's no need to continue any further.
