### ISSUE TITLE
Seeing two errors when gathering data

### ISSUE THREAD

**Issue by danielhoherd** [lpereira/hardinfo#267]
Using a fresh install (2018-06-14) of Ubuntu 16.04, I see some errors when gathering data:

```
# hardinfo -r -f text
Computer
 Summary
sh: 1: /lib/libc.so.6: not found
 Operating System
 Kernel Modules
 Boots
 Languages
 Filesystems
 Display
 Environment Variables
 Users
Devices
 Processor
 Memory
 PCI Devices
 USB Devices
 Printers
 Battery
sh: 0: -c requires an argument
 Sensors
 Input Devices
 Storage
```

Version info:

```
# hardinfo --version
HardInfo version 0.5.1
Copyright (C) 2003-2009 Leandro A. F. Pereira. See COPYING for details.

Compile-time options:
  Release version:   Yes (ARCH_x86_64)
  BinReloc enabled:  Yes
  Data prefix:       /usr/share/hardinfo/
  Library prefix:    /usr/lib/hardinfo/
  Compiled on:       Linux 3.2.0-61-generic (brownie)
Modules:
File Name           Name           Version
computer.so         Computer       0.5.1
devices.so          Devices        0.5.1
network.so          Network        0.5.1
benchmark.so        Benchmarks     0.5.1
```

**Comment by bp0** [comment]
Thanks. As stated in #163, the Ubuntu archive version is very old, and this is mostly fixed. The issue is described in #162.

**Comment by danielhoherd** [comment]
The [latest release that I see here on Github](https://github.com/lpereira/hardinfo/releases) is 0.5.1, which is the same version I see in Ubuntu. Is there a newer version somewhere else?

**Comment by bp0** [comment]
That is the last tagged release, but there have been many changes since
2009. The Debian and Ubuntu 18.04 archives have more recent snapshots.

**Comment by bp0** [comment]
The blockers for @lpereira to tag a new release are listed in #74. They are GTK3 and restore the network sync feature.
