### ISSUE TITLE
Hardinfo creates a .hardinfo folder in the home directory

### ISSUE THREAD

**Issue by newhoa** [lpereira/hardinfo#271]
Hardinfo creates a .hardinfo folder in the home directory. I can't seem to find a reason for this. It doesn't hold any files. Usually .folders are used for configuration files. But Generate Report doesn't auto save to that folder or anything.

If it isn't necessary can it be changed to not create one.

And if it is used for configuration files or other data, can it use a folder defined by [the freedesktop $XDG spec](https://specifications.freedesktop.org/basedir-spec/0.6/ar01s03.html)? 

Cache would go to ~/.cache
Config files go to ~/.config
User data go to ~/.local/share

Most programs use this standard now. It makes a lot of sense, prevents a lot of clutter in the home directory, and makes it easier for a user to find/backup or clear their data since every program doesn't use a different directory.

Thanks.

**Comment by bp0** [comment]
`~/.hardinfo` was moved to `~/.config/hardinfo` (or `g_get_user_config_dir()`) in 06b0d18501c7e25c8d22fa53a9cd5f381334fc44. Some data files can be put there to override the installed versions. It was also used as a cache for the network sync feature that is not currently functional.

**Comment by newhoa** [comment]
Great, thanks for the info! I didn't see that commit when searching around. I'll go ahead and close this. Thanks!
