### ISSUE TITLE
Ryzen 5 1600 benchmark results

### ISSUE THREAD

**Issue by atomsymbol** [lpereira/hardinfo#273]
Hello. Please add the following result to benchmark.data:

    Operating System:
        Gentoo Base System release 2.4.1
    
    Graphics:
        AMD/ATI Hawaii PRO + NVIDIA GeForce GTX 750
        1920x1080
        The X.Org Foundation 1.20.1
        AMD Radeon (TM) R9 390 Series (HAWAII, DRM 3.26.0, 4.18.0, LLVM 6.0.1)
    
    ----
    
    Machine:
        Board:              2.0 / X370 SLI PLUS (MS-7A33) (Micro-Star International Co., Ltd.)
        CPU Name:           AMD Ryzen 5 1600 Six-Core Processor
        CPU Description:    1 physical processor; 6 cores; 12 threads
        CPU Config:         12x 3200.00 MHz
        Threads Available:  12
        GPU:                AMD/ATI Hawaii PRO + NVIDIA GeForce GTX 750
        OpenGL Renderer:    AMD Radeon (TM) R9 390 Series (HAWAII, DRM 3.26.0, 4.18.0, LLVM 6.0.1)
        Memory:             16377260 kiB
    
    CPU Blowfish: 1.05
    Threads: 12
    
    CPU CryptoHash: 1355.67
    Threads: 12
    
    CPU Fibonacci: 1.20
    Threads: 1
    
    CPU N-Queens: 5.20
    Threads: 10
    
    CPU Zlib: 1.85
    Threads: 12
    
    FPU FFT: 0.89
    Threads: 4
    
    FPU Raytracing: 4.61
    Threads: 12
    
    GPU Drawing: 8346.00
    Threads: 0

**Comment by bp0** [comment]
```
#!/bin/sh

# bash just_bench.sh >whatever.conf

do_hi_bench() {
    sleep 1
    echo "[$1]"
    hardinfo -b "$1" -g conf
}

#do_hi_bench "CPU (Single-thread)"
#do_hi_bench "CPU (Multi-thread)"
#do_hi_bench "CPU (Multi-core)"
#do_hi_bench "FPU (Single-thread)"
#do_hi_bench "FPU (Multi-thread)"
#do_hi_bench "FPU (Multi-core)"
do_hi_bench "CPU Blowfish"
do_hi_bench "CPU CryptoHash"
do_hi_bench "CPU Fibonacci"
do_hi_bench "CPU N-Queens"
do_hi_bench "CPU Zlib"
do_hi_bench "FPU FFT"
do_hi_bench "FPU Raytracing"
#do_hi_bench "GPU Drawing"
```

Hi. If you could run this script and post the output, the output will be in a format that will be very easy to merge. In fact, if you want to make things really easy for us, you could also run `crudini --merge data/benchmark.conf < script_output.conf` and then create a pull request.
