### ISSUE TITLE
arm/x86: Better handling required where cpufreq information is not available

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#282]
When cpufreq (or cpuinfo clock) information is not available, there can be results like these observed on a RPi3B running Arch.

`Logical CPU Config: 4x 0.00 MHz`

and

```
Clocks 
- 0.00 MHz - 0.00 MHz: 4x
```
where the clock count is also wrong because relationships aren't available.

**Comment by lpereira** [comment]
Closed by #283.
