### ISSUE TITLE
Code style is not consistent

### ISSUE THREAD

**Issue by MauroMombelli** [lpereira/hardinfo#33]
4 spaces are used for singe identation, while TAB (8 space equivalent) is used for multiple identation.

I suggest the exclusive use of TAB.

Also seems like this code is generated from some automatic tool, maybe from python, and instead of calling directly function, it uses a hastable.

That break many thing like tool to jump to function definition, static tool analysis, and in general the type safeness of c/c++ by using generic argument.

Am i missing something or that part of code can be cleaned up?

**Comment by lpereira** [comment]
The code is quite old (I've started HardInfo in 2003), and I didn't care much about style consistency back then. Part of the reason I've abandoned the project is that I've made some bad decisions and it's too much too work to fix it (the other being that I don't use HardInfo regularly as I've used in the past).

It's written by hand: no automatic tool has been use. I'm curious to know what part you thought that has been written with a tool.

**Comment by MauroMombelli** [comment]
all those "module_call_method_param" where you give the function as string and then use an hast table.. i don't get why sacrifice  compiler check, tool for code analysis and IDE function.. so i was thinking it was auto-generated and left there.

I agree there are many thing to fix in the code, but me and another guy had the idea o resurrect the project, first of all fixing a couple of thing and releasing with a shiny new server, then later working on cleaning up the code. Any suggestion is welcomed, as soon as we have something ready i was thinking to ask to become maintainers, I want't expecting a fast response like that :+1: 

Could you please tell me more about the server protocol? i found out you use RPC + XML and there are just two function, one to get server version (must be 1) and the other to upload data, right?

also what is benchmark.data? is that in the format that should be uploaded/downloaded? i still have to look at the code, what is its format?

**Comment by lpereira** [comment]
Thanks for trying to ressurect HardInfo! If you have any questions, please ask.

Ah, `module_call_method_param()` must be that way. That's because each module (computer, devices, etc.) communicate back to the shell by passing back strings formatted in a certain way. And that's the way a module can request information from another module; for instance, the computer module can obtain information from the devices module to build the summary information.

Modules can also obtain information from the same module by calling this function from the C code as well; IIRC that's how the benchmark module gets which CPU it's running on. The idea is that people could write their own modules but this never happened, so I would do this differently today.

The server protocol for synchronizing stuff indeed uses XML-RPC. You're right about the two remote functions. The one to upload/retrieve data is used by many other functions; grep for calls to `sync_manager_add_entry()`. Some things have their own format (like `pci.ids` file for lspci), but most (including vendor list, CPU flag list, benchmark data) are in the GLib GKeyFile format, which is essentially a format inspired by Windows `.ini` files.

**Comment by Woowoo678** [comment]
Any update on this with regard to resurrecting HardInfo?

**Comment by mckaygerhard** [comment]
hardinfo can receive pull request with contributions, so "resurrectiing" depends of u'r contrubutions @Woowoo678 i made somes ago some contribution, and i'll made more in near future when i v' less work in my job

**Comment by Woowoo678** [comment]
In particular, I was referring to @MauroMombelli's idea of perhaps becoming a maintainer of hardinfo

**Comment by lpereira** [comment]
Well, there are quite a few things that can be fixed and/or improved. Send a few pull requests fixing those, etc, and maybe I'll pass the baton to you.

**Comment by Woowoo678** [comment]
I'm unsure as to how well suited I'd be towards such an undertaking. I still consider myself a amateur with software development, and don't really have experience with actually maintaining a software project, nor do I really have an in-depth knowledge of build systems yet. I also don't yet know whether I could keep up with the commitment involved.

I've considered at least trying to learn such skills, but that would only be if there's literally no other chance of this project being picked up

**Comment by mckaygerhard** [comment]
i think can be done some mixure of ideas.. 

more than one mantainer can handle the proyect, with @lpereira  as coordinator, a issue organizator, a few developers commiters (ultimatilly there some commit and pulls requests) this topic can be assumed done!

i can help in organize documentation,a nd attention to the issues help .. also some code in some times... but prefer to handle issue organization and documentation wiki/code

**Comment by MauroMombelli** [comment]
Sorry to jump in only now, times ago I look at the code with a friend, and
we decided to not maintenance it as for what we had in mind (a "classic"
control panel) was basically to be rewritten. Also it use multiple
different method to get data from the system, sometimes parsing shell
output..
Some command can be replaced with less call to different command, maybe
there wasn't at the time, I don't remember exactly what (maybe lshw?)

For sure a more deep explanation of some gotchas is required

On Mon, 6 Mar 2017, 15:34 PICCORO Lenz McKAY, <notifications@github.com>
wrote:

i think can be done some mixure of ideas..

more than one mantainer can handle the proyect, with @lpereira
<https://github.com/lpereira> as coordinator, a issue organizator, a few
developers commiters (ultimatilly there some commit and pulls requests)
this topic can be assumed done!

i can help in organize documentation,a nd attention to the issues help ..
also some code in some times... but prefer to handle issue organization and
documentation wiki/code

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lpereira/hardinfo/issues/33#issuecomment-284412458>,
or mute
the thread

**Comment by mckaygerhard** [comment]
in last message of #33 author said that issue must be assumed as done, please close it!

**Comment by bp0** [comment]
Please subscribe to #102 and #100 if still interested in following this issue.
