### ISSUE TITLE
No Storage Info

### ISSUE THREAD

**Issue by ismet** [lpereira/hardinfo#344]
I cannot see any storage information:

![image](https://user-images.githubusercontent.com/109025/59178176-f7b0e080-8b66-11e9-9e40-a6f2ed30e33f.png)

The output of `lsscsi -c ` command:
`[N:0:2:1]    disk    SAMSUNG MZVPW256HEGL-00000__1              /dev/nvme0n1
`

**Comment by ocerman** [comment]
Hello, thanks for your report.
What version of hardinfo are using ? And what OS/Distro?

**Comment by ismet** [comment]
I have Arch Linux and use the official community package. 
[https://www.archlinux.org/packages/community/x86_64/hardinfo/](https://www.archlinux.org/packages/community/x86_64/hardinfo/)

The package version is 0.5.1.816.g877ea2b-1
The program's version is 0.6-alpha
![image](https://user-images.githubusercontent.com/109025/59185304-c04b2f80-8b78-11e9-9abe-e8a0dda468ec.png)

**Comment by ocerman** [comment]
@ismet Unfortunatelly that version is outdated, there was no support for nvme devices. Current version (from git/master) should show NVMe devices (as it is using udisks2, it was added in January #330).

**Comment by ismet** [comment]
@ocerman Thank you. 

I wonder why no new version has been released since 2009.

**Comment by lpereira** [comment]
The reason is that I lost interest in the project.  But then people like @bp0, @ocerman, @TotalCaesar659 showed up and began sending patches.  Some people want to package newer versions in their distros, so I'm thinking about releasing a new version; just have to reinstate the update server before I do this.

**Comment by lpereira** [comment]
Closing this issue as it's fixed already.

**Comment by l4jos** [comment]
This is not fixed yet (not for me anyway). Storage info does not show anything with default settings.
I tried it out to know if my notebook storage device is a HDD or SSD.

The storage info from hdparm -I /dev/sda is not empty as I can read it with sudo (only with sudo).
$ hdparm -I /dev/sda > permission denied
$ sudo hdparm -I /dev/sda > 

Specs:
HP Elitebook 2170s.
Parrot OS (Debian based).
Hitachi HTS725032A7E630

**Comment by bp0** [comment]
That version of Hardinfo is too old to give that information. You'd need to use one that you build from source.

Anyway, HTS725032A7E630 appears to be a 7200RPM spinning hard disk.
