### ISSUE TITLE
Sensors values bugged on update

### ISSUE THREAD

**Issue by ocerman** [lpereira/hardinfo#358]
![sensors](https://user-images.githubusercontent.com/10187350/59968279-64e54e00-9537-11e9-9b82-69b4ca410e60.png)

This issue seems to be introduced in 80c9eede822f4d2466bdead6d0b58ec49477401b , however I don't know why.

**Comment by ocerman** [comment]
Sensor values are fine after sensor page gets loaded, or when clicking on "Refresh" button. However it is bugged on Update.

**Comment by bp0** [comment]
Ah, sorry:
It is here: https://github.com/lpereira/hardinfo/commit/80c9eede822f4d2466bdead6d0b58ec49477401b#diff-230a94500bd8ad5db143066a93bd83d1L528

**Comment by bp0** [comment]
#359 should fix it.
