### ISSUE TITLE
Hardinfo/GTK3 : Missing benchmarks

### ISSUE THREAD

**Issue by jurobystricky** [lpereira/hardinfo#362]
When I built hardinfo (for Clear Linux) with GTK3, the whole section of "Benchmarks" was missing. "Generate Report" dialog did not show benchmarks either.  This is probably done on purpose, and falls under "guibench is disabled for gtk3." , nevertheless I felt compelled to mention this hoping there is a remedy by now.

https://github.com/lpereira/hardinfo/issues/112 (July 2017)

**Comment by lpereira** [comment]
Fixed with #370.

**Comment by sTiKyt** [comment]
Are you sure it's fixed?
