### ISSUE TITLE
DMI Memory location conflict

### ISSUE THREAD

**Issue by ocerman** [lpereira/hardinfo#386]
First of all, thanks @bp0 for Unifying DMI/SPD, it is much better experience now.

I have one issue in my box. My BIOS is reporting DIMM numbers for each channel separately. So I see 2x DIMM 0 and 2x DIMM1 in the list. This is (propably) also causing the issue that same "more info" is loaded for both sticks (look at DMI handle).

I suggest we could change Locator string by adding "Bank locator". So on my system it would be like Mainboard > P0 Channel A > DIMM 0.

DMI decode -t memory output:  [dmimem.txt](https://github.com/lpereira/hardinfo/files/3342870/dmimem.txt)
Hardinfo report: [hadinfomemdev.txt](https://github.com/lpereira/hardinfo/files/3342871/hadinfomemdev.txt) (also sorry @bp0, i have just noticed that you were asking for this in #369 )

**Comment by bp0** [comment]
Hmm something else is wrong too: the SPD vendor should have been pulled up in to the DMI vendor field to replace the "Unknown"s. ([Code for that](https://github.com/lpereira/hardinfo/blob/master/modules/devices/dmi_memory.c#L301,L304))

Anyway, about your original issue, that is a good suggestion. Although, to try and keep it short I think I will first only including Bank Locator when there are duplicate locators. I already shortened "System Board Or Motherboard" to just "Mainboard".

What is the model of motherboard if I may ask?

**Comment by ocerman** [comment]
It is ASRock B350 Pro4

As for the Unknown manufacturer: It seems that the problem is that there is [no check](https://github.com/lpereira/hardinfo/blob/master/modules/devices/dmi_memory.c#L237) for "Unknown", only for "\<BAD INDEX\>"

**Comment by bp0** [comment]
I have an ASUS PRIME B350 PLUS, which seems to be the ASUS version of that board, and mine are:
```
Mainboard > BANK 0 > DIMM_A1
Mainboard > BANK 1 > DIMM_A2
Mainboard > BANK 2 > DIMM_B1
Mainboard > BANK 3 > DIMM_B2
```
So Bank Locator doesn't really tell me anything.

**Comment by bp0** [comment]
Also I have an HP Board with:
```
Mainboard > BANK 0 > DIMM_1
Mainboard > BANK 1 > DIMM_2
Mainboard > BANK 2 > DIMM_3
Mainboard > BANK 3 > DIMM_4
```
Bank Locator again seems meaningless.

**Comment by ocerman** [comment]
I have tested some more systems and it seems like my ASRock board was the only one that showed someting usefull in "Bank locator"
