### ISSUE TITLE
CPU Vulnerabilities strangeness

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#392]
Sometimes the vulnerabilities list is incomplete in the GUI, but leaving and then returning fixes it. 

![Screenshot from 2019-07-01 00-27-40](https://user-images.githubusercontent.com/1758090/60412583-4adee780-9b97-11e9-9725-0c90e797c76d.png)

Here is the `hardinfo -r -f shell -s -w`:
```
Security
--------

[HardInfo]
HardInfo running as=User
[Health]
Available entropy in /dev/random=...
[Hardening Features]
ASLR=Fully enabled (mmap base+stack+VDSO base+heap)
dmesg=User access allowed
[Linux Security Modules]
Modules available=capability,yama,apparmor
SELinux status=Not installed
[CPU Vulnerabilities]
spectre_v2=Mitigation: Full generic retpoline, IBPB: conditional, IBRS_FW, STIBP: disabled, RSB filling
mds=Mitigation: Clear CPU buffers; SMT disabled
l1tf=Mitigation: PTE Inversion; VMX: conditional cache flushes, SMT disabled
spec_store_bypass=Mitigation: Speculative Store Bypass disabled via prctl and seccomp
spectre_v1=Mitigation: __user pointer sanitization
meltdown=Mitigation: PTI
[$ShellParam$]
UpdateInterval$Available entropy in /dev/random=1000
ViewType=0
ShowColumnHeaders=false
```

**Comment by lpereira** [comment]
I was able to reproduce this once last evening, too.  Don't know what triggered it, but with the new DisplayView thing, it became evident that, for some reason, flattening a struct Info is being stopped in the middle (ViewType doesn't get set, and information is shown in a list instead).

**Comment by bp0** [comment]
I think the problem is that const gchar* vuln (computer.c line 613) is owned by glib, and is invalid after g_dir_close(), but it is used as the field name. InfoField.name is also const, so it can't be just strdup()ed.

**Comment by lpereira** [comment]
That makes sense. Pushed some changes addressing this issue.
