### ISSUE TITLE
Show icons for kernel modules

### ISSUE THREAD

**Issue by lpereira** [lpereira/hardinfo#406]
It would be nice if icons could be shown for kernel modules, based on the type of the device that is using that kernel module.  This is possible for PCI devices and graphics cards, should be possible for USB devices too.

Same icons could be shown in the Resources view.

**Comment by bp0** [comment]
I think it might be simpler to just use a table of known modules to icons.

**Comment by lpereira** [comment]
HardInfo is now using the file path to determine the icon.
