### ISSUE TITLE
Memory SPD: Please load eeprom module to obtain information about memory SPD

### ISSUE THREAD

**Issue by sonichy** [lpereira/hardinfo#426]

**Comment by bp0** [comment]
Yes, that's right.

I'll guess that this is supposed to be a question though, so I'll answer `sudo modprobe eeprom`. I notice that is an old version of the hint message. (See #163) Please use a more recent version of HardInfo, if possible.

**Comment by sonichy** [comment]
You should add message of [sudo modprobe eeprom] there.
After [sudo modprobe eeprom], the [Bank, Size, Manufactureer, Model] is empty.

**Comment by lpereira** [comment]
It may be the case that you're using a computer with DDR4 memory. If that's
the case, you'll want to update your copy of HardInfo, as the version
you're using does not support it. Unfortunately, it requires a different
kernel module and some manual configuration in order to be able to decode
DDR4 SPDs.

**Comment by sonichy** [comment]
DDR3

**Comment by bp0** [comment]
The eeprom module needs to find an SPD eeprom on a special i2c bus called SMBus. 

To try and figure out what may be happening, first check `ls /sys/bus/i2c/drivers/eeprom/` to see if there are any eeproms found at all. The SMBus will have address parts X-0050 to X-0057. If there are some there, but HardInfo shows nothing, then it is a bug in HardInfo. If there are none there, then it means the eeprom module could not find any. Try `sudo i2cdetect -l | grep smbus`, and if nothing is listed, then there is no SMBus, or no driver support for yours.

I have an old Phenom II system with an AMD SB700 chipset that has an SMBus controller, but no i2c bus is found on it in Linux. On that system, the eeprom module finds no SPD eeprom. It could be something like this.

**Comment by sonichy** [comment]
After `sudo apt-get install i2c-tools`
`sudo i2cdetect -l | grep smbus`
i2c-0	smbus     	SMBus I801 adapter at f040      	SMBus adapter
But `/sys/bus/i2c/drivers/` has no folder `eeprom`

**Comment by bp0** [comment]
What is the result of `sudo i2cdetect -y 0 0x50 0x57` ?

**Comment by sonichy** [comment]
0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                                                 
10:                                                 
20:                                                 
30:                                                 
40:                                                 
50: -- -- -- -- -- -- -- --                         
60:                                                 
70:

**Comment by bp0** [comment]
This shows that no SPD eeprom was found on the bus. If so, some of the `--` would be numbers or `UU`.

**Comment by bp0** [comment]
In more recent Hardinfo, the memory SPD function has been merged with memory information from DMI, and called "Memory Devices". Perhaps if you try building the latest from git, and run Hardinfo with sudo, you can get more information.
