### ISSUE TITLE
make/update manpage to tell/show common options of hardinfo 

### ISSUE THREAD

**Issue by shirishag75** [lpereira/hardinfo#45]
Please make or/and update manpage to tell/show common options of hardinfo.

**Comment by mckaygerhard** [comment]
some times ago i made a manpage.. but not finish the install code.. i'll try to do something at my vacations.. in a coupe of weeks

**Comment by mckaygerhard** [comment]
the manpage pull are ready and install rule made it! to close this with #54

**Comment by mckaygerhard** [comment]
this issue are solved.

**Comment by bp0** [comment]
Added in 8d46f3861d016fba2e309f5c8282362233bc6caa
