### ISSUE TITLE
How to Add a Benchmark Result

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#458]
It would be nice to have some more bench result for comparison, but I have only a few machines, so help from others is needed and requested.
Until an automatic bench submission framework is complete, here is the best way to submit bench results to Hardinfo.

First:
Fork Hardinfo, build and install following the instructions at https://github.com/lpereira/hardinfo/issues/325#issuecomment-493809219, modifying them to pull from YOUR FORK.

Then:
```bash
# From the hardinfo git root, run:
git checkout -b myresult
cd build 
# The build directory should exist from building the latest Hardinfo.
# Using `build/` will keep the git tree clean.
bash ../test/just_bench.sh >mybench.conf
crudini --merge ../data/benchmark.conf <mybench.conf
# Examine the changes:
git diff
# Only benchmark.conf should change, and the added lines 
# should be the new results.
git add ../data/benchmark.conf
git commit -m "add bench result ..."
git push -u origin myresult
# Go to https://github.com/lpereira/hardinfo and open a Pull Request.
```

**Comment by lpereira** [comment]
I've yet to reinstate the server. Been pretty busy with the move, and I've
yet to get an actual internet connection at home to finish this. Once it's
done, this should be easy...

**Comment by bp0** [comment]
I think this process will do, but until all that can be done, but I wonder if it would be worth it to have an "Export Result" that would create a block of text that could be pasted into a thread like this.

**Comment by lpereira** [comment]
Can't make a PR right now, but here's some results:
[results.txt](https://github.com/lpereira/hardinfo/files/3557343/results.txt)

**Comment by lpereira** [comment]
This shouldn't be needed anymore: the server has been reinstated and sending a new benchmark result is just the matter of sending the results to the server.  (It'll be available in the next 12h or so.)

**Comment by lpereira** [comment]
Closing issue as the server stuff seems to be working fine now.
