### ISSUE TITLE
Incorrect Size in Memeory SPD

### ISSUE THREAD

**Issue by kinkingmax** [lpereira/hardinfo#464]
The size in hardinfo is 8192MB. But it is a 4096 MB DDR 3 memory. 
I can provide any information you required.

**Comment by bp0** [comment]
In the SPD information there is a field called "Source", it should be something like "0-0052".

Please run `hexdump -v -e '16/1 "%02x""\n"' /sys/bus/i2c/drivers/eeprom/0-0052/eeprom`, but replace `0-0052` part with whatever your actual "Source" was, and paste the result in this thread.

A screenshot of Hardinfo showing the erroneous result would also be helpful.

**Comment by kinkingmax** [comment]
I already dump out using i2cdump
≥ sudo i2cdump -f -y 0 0x50                                                                                                                                                              9:38
No size specified (using byte-data access)
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 92 10 0b 03 04 19 02 0a 03 52 01 08 0a 00 fe 00    ?????????R???.?.
10: 69 78 69 3c 69 11 18 81 20 08 3c 3c 01 40 83 05    ixi<i??? ?<<?@??
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
30: 00 00 00 00 00 00 00 00 00 00 00 00 0f 11 00 00    ............??..
40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
70: 00 00 00 00 00 04 ef 00 14 27 00 00 00 00 b9 0c    .....??.?'....??
80: 54 65 61 6d 2d 45 6c 69 74 65 2d 31 36 30 30 20    Team-Elite-1600 
90: 20 20 00 00 04 ef 00 00 00 00 00 00 00 00 00 00      ..??..........
a0: 10 14 07 01 01 70 00 00 00 00 11 14 07 02 04 50    ?????p....?????P
b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
value of 0x04h is 04. And this is a DDR3 RAM. So it should be 4GB. 
And screenshot attached following. 
![Hardinfo_incorrectSize](https://user-images.githubusercontent.com/47803023/64398232-9d0c1f80-d096-11e9-8106-bf6ba141d218.png)

**Comment by kinkingmax** [comment]
Add output of hexdump
92100b030419020a035201080a00fe00
6978693c6911188120083c3c01408305
00000000000000000000000000000000
0000000000000000000000000f110000
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
000000000004ef00142700000000b90c
5465616d2d456c6974652d3136303020
2020000004ef00000000000000000000
10140701017000000000111407020450
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000

**Comment by bp0** [comment]
Ah, you are using an old version of Hardinfo. This bug was fixed in https://github.com/lpereira/hardinfo/commit/0888ccbf4a7188cbb0d0e5572137c593aa0c5a6c. This bug is a duplicate of #345. If you use master, the information should be correct.

**Comment by kinkingmax** [comment]
Is this the newest version?
![Hardinfo_incorrectSize_2](https://user-images.githubusercontent.com/47803023/64398995-6388e380-d099-11e9-93fd-001ba67115d3.png)

**Comment by bp0** [comment]
It is probably the newest packaged version, but unfortunately there has not been a new tagged version for 10 years, so it is actually very old. Really the only thing to do at this time is to build hardinfo yourself from git master. Hopefully very soon @lpereira will be comfortable with a new version.

**Comment by kinkingmax** [comment]
This is the one I self complied from git master. After rebooting, the memory info is corrected. 
This issue can be marked as 'fixed',
