### ISSUE TITLE
Application crashes on start

### ISSUE THREAD

**Issue by pawanneupane** [lpereira/hardinfo#468]
I'm running Arch Linux with Cinnamon DE. Whenever I try to open System Profiler, it crashes with the following error:

`Aborted (core dumped)`

**Comment by pawanneupane** [comment]
Apparently, the issue was related to the GTK theme I was using - Arc Darkest. It works fine after switching to Matcha Dark Sea theme.

**Comment by pawanneupane** [comment]
Apparently the issue was related to the GTK theme I was using - Arc Darkest. It works fine after switching to Matcha Dark Sea theme.

**Comment by GraveDigger1** [comment]
i know this is closed but i can't see switching themes to satisfy SPaB. Is there anything that i can do? thanks

global theme - aritim-dark
application style gtk2 theme: aritim-dark-gtk, gtk3 theme: aritim-dark-gtk

manjaro kde 18.1.5 rc2 testing build
