### ISSUE TITLE
Firmware shows strange characters

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#469]
Reproducible, but I don't understand it yet. VersionFormat's 't' is replaced by character `0001` for Unifying Receiver.

![Screenshot_2019-09-21_20-40-58](https://user-images.githubusercontent.com/1758090/65381134-5d595080-dcb0-11e9-9dd3-105e10a1fafa.png)

**Comment by ocerman** [comment]
It is possible that #517 fixes this, @bp0 can you try it?

**Comment by bp0** [comment]
I don't see the problem, but I also don't see the VersionFormat item that it occurred in. Is VersionFormat not supplied when using the D-Bus interface?

**Comment by lpereira** [comment]
Fixed in #517.

**Comment by ocerman** [comment]
I just noticed that VersionFormat is not displayed. Actually, it is supplied by D-Bus, but not as a string, but as a number representing enum. So this can be added, however I do not think this is particular useful information ...
