### ISSUE TITLE
Free stickers for contributors

### ISSUE THREAD

**Issue by lpereira** [lpereira/hardinfo#472]
![EHRokwZU8AAlWVX](https://user-images.githubusercontent.com/15001/67215793-f7f39f00-f3d6-11e9-883f-cfab4f39ecc0.jpg)

If you want one, just send me an email.

**Comment by mckaygerhard** [comment]
it seems that I will not be able to enjoy them for many emails that I send you ... where I am they will never reach me

**Comment by lpereira** [comment]
I have not received emails from you. That's strange. (I haven't sent the
stickers yet to anybody though.)

**Comment by mckaygerhard** [comment]
i not send any.. due i'll not will receive due in my country will not be available X-D dont worry men! cannot be possible !

**Comment by lpereira** [comment]
Stickers have been sent to those that gave me an address.  I'm closing this issue for now, but the offer still stands: if you ever had a patch merged in HardInfo, I'll send a sticker!

(If you get them, I'd appreciate a picture of it in your laptop lid or whatever.)
