### ISSUE TITLE
Incorrect labels for mouse USB interface: problem with usb.ids parsing

### ISSUE THREAD

**Issue by ocerman** [lpereira/hardinfo#476]
I just noticed that hardinfo is returning incorrect subclass and protocol labels for the mouse USB interface (class 03/subclass 01/protocol 02).

@bp0 I think the problem is in `scan_ids_file` as this minimal example is returning `Human Interface Device/Printer/Bidirectional`:
```
scan_ids_file(usb_ids_file, "C 03/01/02", &result, -1);
printf("%s/%s/%s\n", result.results[0], result.results[1], result.results[2]);
```

**Comment by bp0** [comment]
Yeah it must be. I'm traveling and it may be a couple days before I can
look it properly.
