### ISSUE TITLE
Memory Vendors string issue

### ISSUE THREAD

**Issue by ocerman** [lpereira/hardinfo#493]
![hardinfo-memi](https://user-images.githubusercontent.com/10187350/71522743-3ec5af80-28c6-11ea-854d-0cbaebb57175.png)

**Comment by bp0** [comment]
I'd like to show the actual value read and the vendor match information. The way it is done now, aside from the missing space, looks redundant. I have been working on a solution where the actual value is used as the field value, with the vendor match info added below it:

![Screenshot_2019-12-27_18-24-08](https://user-images.githubusercontent.com/1758090/71536539-2067b000-28d6-11ea-8021-a4fea78d56da.png)
![Screenshot_2019-12-27_18-12-36](https://user-images.githubusercontent.com/1758090/71536540-2067b000-28d6-11ea-8a76-97e78ab71b39.png)

**Comment by bp0** [comment]
Fixed in #494
