### ISSUE TITLE
bench_value_from_str() doesn't handle weird euro floats with comma for decimal

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#497]
Thanks to @ocerman 's bench result (4c386e89eb9bf28e43164b958374bee113b4cee7) it is discovered that sscanf("%lf") is unreliable!

Complete a benchmark in 0 seconds! The new Ryzen's are truly amazing.

**Comment by ocerman** [comment]
I just noticed I have different problem - Look at these old i5s
![bench](https://user-images.githubusercontent.com/10187350/71542805-1f349280-296b-11ea-9a54-3fed887e7065.png)
