### ISSUE TITLE
More temperature indicators in HardInfo than in sensors

### ISSUE THREAD

**Issue by Petrouchka** [lpereira/hardinfo#523]
With HardInfo, I've got 7 temperatures. With sensors, I've got only 6 temperatures.
Is it a bug with HardInfo or is a temperature missing in sensors ?

![image](https://user-images.githubusercontent.com/3955499/72614799-7a86ee80-3933-11ea-8fb5-bea4b11c3a1c.png)

sensors version 3.4.0 with libsensors version 3.4.0
HardInfo 0.6-alpha

**Comment by bp0** [comment]
`sensors` only shows hwmon (smbus/i2c) sensor values. Thermal zone from
firmware and disk temperatures from udisks2 are also reported in hardinfo's
sensors view.

**Comment by Petrouchka** [comment]
So, sensors doesn't show /sys/class/thermal/thermal_zone0/temp, isn't it ?

**Comment by bp0** [comment]
Right.

**Comment by Petrouchka** [comment]
Thank you for the explanation.
