### ISSUE TITLE
Cant build on Solus

### ISSUE THREAD

**Issue by Mark12870** [lpereira/hardinfo#527]
Hello,
while I execute  `cmake` command, it shows me
```
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  CMakeLists.txt:84 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/marek/Downloads/hardinfo-master/build/CMakeFiles/CMakeOutput.log".
```

Here is the log:
[CMakeOutput.log](https://github.com/lpereira/hardinfo/files/4099067/CMakeOutput.log)

What exactly am I missing?

**Comment by lpereira** [comment]
Can you please share the whole build log too -- the output of running cmake on a clean directory, not the contents of CMakeOutput.log?

**Comment by bp0** [comment]
You need the Solus version of Debian's libgtk2.0-dev ( >= 2.10)

**Comment by Mark12870** [comment]
Thank you for help, I installed that lib and I was able to build it. :+1:
But right now I've got another problem. I can't execute it:
```
marek@marek-solus-pc ~/Downloads/hardinfo-master/build $ ./hardinfo

** (hardinfo:5580): ERROR **: 18:08:59.237: Failed to find runtime data.

• Is HardInfo correctly installed?
• See if /usr/local/share/hardinfo and /usr/local/lib64/hardinfo exists and you have read permission.
Trace/breakpoint trap
```

Well, directory `/usr/local` doesnt even exists on my system. :/

**Comment by bp0** [comment]
Hardinfo must be installed with `sudo make install`

**Comment by Mark12870** [comment]
I see, thank you for help, it works now :)
