### ISSUE TITLE
Reinstate the server

### ISSUE THREAD

**Issue by lpereira** [lpereira/hardinfo#532]
When HardInfo was hosted by Berlios, it used to have a PHP script that would gather benchmark data from users and send them back, while also provide up-to-date files (CPU ID, vendors, PCI IDs, etc).  It would also try to average out results from machines with the same specs over time.  Unfortunately, Berlios decided it would no longer host stuff there and I ended up ignoring the warnings they would delete everything; of course I had no backup.

For the next release, I want to have the server back.  This time, I'll host it myself to avoid gotchas.  The idea is:

1. Write it in Go, rather than PHP. (Easier to deploy, especially in the VPS I already pay for other purposes.)
2. Source code will be in this repository, but in a different branch.  This way I won't lose the source code again.
3. Any non-benchmark data will be downloaded from GitHub, so it's easier for us to update it.

I don't know, however, how this is going to play out with laws like GDPR in Europe and whatnot.  I don't know if I can store this kind of data indefinitely.  It's anonymous, and I won't store any logs, but you never know.

I'd like to change, however, the benchmark format from the current pipe-delimited file to something that's more descriptive (JSON, maybe), because it's easier to maintain.  (Since this file will be generated by the server, I don't want us to maintain two pieces of code that reads and generates this in different languages, different places, etc.  With a more descriptive format, this is a lot easier.  Plus, generating JSON with Go is very easy.  I think it's fine to break the current format because HardInfo wasn't released with it yet; @bp0, thoughts?)

**Comment by lpereira** [comment]
Started writing the server this morning.  Since older HardInfo clients won't be able to resolve `hardinfo.berlios.de` anymore, I've changed the API.  This time around the endpoint will be in a domain I control so it's always there.

[Current code is here](https://gist.github.com/lpereira/a7592d743ef864d59122d96296e64f14).  Once it's complete, I'll push to this repo in a separate branch.  It'll probably use SQLite as it's good enough for this task, but I can migrate to something like MySQL if there's the need.

Will also have to change how benchmark results are read, as I'll probably just store the received JSON file.

I might change `GetUrlForFile()` to act as a caching proxy, though, to reduce the number of connections necessary to obtain one of those files.  Not sure yet.

There are some TODOs that I eventually had to do in the previous version, so I'll implement here to avoid the same kind of issues; they should be easy enough to do, and don't need to be the kludge it used to be.

**Comment by lpereira** [comment]
Decided to rewrite the thing completely.  Since it's an API-breaking change, might as well get rid of XML-RPC and make something nicer.  New version is [being developed here](https://cornputer.org/lpereira/hardinfo-server), but I'll put in this repo whenever it's ready.

The idea is that HardInfo will only request, though HTTP, things like "/pci.ids", "/usb.ids", "/benchmark.json", etc.  It'll then proceed to download from GitHub and cache the result in the server.  For `benchmark.json`, it'll generate the data from the database and update the cached blob if it's time to update.  To publish a benchmark result, just make a POST request to `/benchmark.json` with a benchmark result in JSON format and it'll be added to the benchmark.

A lot simpler than what was in place before.

I'll just have to write a script to convert our `benchmark.conf` format to JSON, and modify the reader to parse JSON format.  It's more verbose, but it's also easier to work with.

**Comment by lpereira** [comment]
Worked a little bit more on it today.  Now it fetches "pci.ids" and "usb.ids" from their original sources, so users can always have a fresh version even if their distro is slow to update them (and we don't need to update the repo every time those files change!).  Other files, like "vendors.conf", will be fetched directly from our repo, so it's easy for it to be changed while having version history and whatnot.

For the benchmarks, when generating a "benchmarks.json" to be cached, it'll average the results for the same benchmark, machine_id, and pointer_bits.  The old server used to do this via a cron job, but in this server, it's just done as part of the normal caching method.

Now I have to change HardInfo to understand the JSON format, and then write a scrip to convert "benchmark.conf" to JSON and publish it to the server, so we have a "seed value".

Then it's just the matter of running the benchmarks and synchronizing with the server.  I have a handful of machines here I can run them.

**Comment by lpereira** [comment]
I'm working on right now in the ability to query CPU information by using stuff discussed in #373. Starting with Wikichip as they have a public API.

**Comment by leogx9r** [comment]
@lpereira Any progress on this?

**Comment by lpereira** [comment]
Spent some time today writing a script to convert `benchmark.conf` to `benchmark.json` in the format the server will accept, and started cleaning up the C code in SyncManager and the benchmark value loader.  Everything has been pushed to this repo.

Next I'll have to port the loader to load from JSON files, and make it generate JSON files to talk with the new server.

I'll leave the CPU information stuff for another revision; it can always be added later.  It's better to just reinstate the feature set of the old server.

**Comment by lpereira** [comment]
I've also moved the server repository to this repository, under the `server` branch.  This should make it easier for people to contribute to it, too.

**Comment by lpereira** [comment]
JSON loading is now working after some mild refactoring!  HardInfo from HEAD will prefer loading a "benchmark.json" in either `~/.config/hardinfo` or `share/hardinfo/hardinfo` before trying to load `benchmark.conf`.  Once this stabilizes, we can probably remove the loader from `benchmark.conf`.

Now it needs to save data in JSON, and the SyncManager has to learn the new API. Then I just need to install it somewhere and this will be finally done!

**Comment by lpereira** [comment]
JSON is now generated.

Only the SyncManager stuff remains. It's close :D

**Comment by lpereira** [comment]
Alright -- SyncManager stuff done.  Set up DNS for `api.hardinfo.org`, but this is probably going to take a while.  Maybe tomorrow I'll take a look and deploy the server on a VPS I have.

Also made changes that will make every sysobj_early dep ID file updatable; just push a new version to the data directory and hardinfo will be able to update it. Easy :)

**Comment by lpereira** [comment]
Done!  Server is running, HardInfo now knows how to talk with it.  Send your benchmark results!

**Comment by lpereira** [comment]
It seems that the server is not storing the benchmark results properly. Need to see why that's happening today.

**Comment by lpereira** [comment]
Found the issues and fixed them.  *Now* you can send the benchmarks :D

**Comment by leogx9r** [comment]
Awesome work, will get to this :)
