### ISSUE TITLE
Bench Results: Extra Info and User Note display problems

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#552]
Text is replaced by underscores. Data in benchmark.json looks ok.
![Screenshot_2020-05-27_00-48-25](https://user-images.githubusercontent.com/1758090/82982634-35935880-9fb4-11ea-9026-9f9d883a8ef2.png)

**Comment by bp0** [comment]
Is a pointer really 64 bits on that ARM running in 32-bit mode? Hmm.

**Comment by lpereira** [comment]
It was a stupid mistake.  It's been fixed; please confirm.
