### ISSUE TITLE
error raised depends of libsoup to 2.42 as minimum

### ISSUE THREAD

**Issue by mckaygerhard** [lpereira/hardinfo#562]
when try to compile in varous mixed scenarios libsoup are not copatible anymore:

```
[  121s] CMakeFiles/hardinfo.dir/shell/syncmanager.c.o: In function `got_response':
[  121s] /usr/src/packages/BUILD/shell/syncmanager.c:244: undefined reference to `soup_session_send_finish'
[  121s] CMakeFiles/hardinfo.dir/shell/syncmanager.c.o: In function `send_request_for_net_action':
[  121s] /usr/src/packages/BUILD/shell/syncmanager.c:292: undefined reference to `soup_session_send_async'
[  121s] CMakeFiles/hardinfo.dir/shell/syncmanager.c.o: In function `sync_dialog_start_sync':
[  121s] /usr/src/packages/BUILD/shell/syncmanager.c:210: undefined reference to `soup_session_new_with_options
```

seem `soup_session_send_finish` are since 2.42 and `soup_session_send_async` but .. seems code are not understandable for me:

https://github.com/lpereira/hardinfo/search?q=got_response&unscoped_q=got_response

from commit d87090f1496accde2c0f981a2110f3080c7a2000 so due that "block ui" fancy feature async it could not compile in mostly versions.. 

umm unfortunatelly i not have a proper funtion here to check: https://developer.gnome.org/libsoup/stable/libsoup-2.4-Version-Information.html seems all was added since 2.42 and i need to check 2.32 to 2.42.. oufff

so based on Depends on glib2.0 >= 2.36 according to configure.ac i simply check for that glib version and so then libsoup are enough recent!

**but this dont work so the better is to disable libsoup and sync report for olders libsoup detected versions, so due raised depends.. cmakelist must be fixed**

**Comment by mckaygerhard** [comment]
errr @lpereira  README.md has older info due https://github.com/lpereira/hardinfo/commit/b3078492f75d0694cbfc6c002fb267250877483d#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by lpereira** [comment]
Just send a PR.

**Comment by mckaygerhard** [comment]
> Just send a PR.

merge the pr! ..

**Comment by mckaygerhard** [comment]
now works ! @lpereira  merge https://github.com/lpereira/hardinfo/pull/564
