### ISSUE TITLE
Synchronization: we will see translated strings when update in progress only

### ISSUE THREAD

**Issue by Skif-off** [lpereira/hardinfo#572]
I mean strings
```
Update PCI ID listing
Update USB ID listing
Update EDID vendor codes
Update IEEE OUI vendor codes
Update SD card manufacturer information
Send benchmark results
Receive benchmark results
Update vendor list
```
in Synchronization window, they are without translation, but after starting the update HardInfo begins to show translated strings.
I can't find suitable words for descript :), but I created small GIF animation
![example](https://user-images.githubusercontent.com/6333198/88017600-0f62e280-cb37-11ea-8385-9f7ab03f0e72.gif)

**Comment by lpereira** [comment]
Oops. Yes, that's an easy fix. Will send a patch tonight.

**Comment by lpereira** [comment]
Please let me know if this fixes the issue.

**Comment by Skif-off** [comment]
Thanks, but not everything works: second window (with `Synchronizing\nThis may take some time.`) looks fine now, but first (with checkboxes) looks the same, i.e. without translation.

**Comment by lpereira** [comment]
Reopening issue then. Will look at this this week

**Comment by lpereira** [comment]
Alright, found two other places where calls to get the translated text were not being made and fixed those.  Could you please test again, @Skif-off?

**Comment by Skif-off** [comment]
Thank you! Now all strings with translation.

Moving the link to the Privacy Policy looks a little strange because in some languages the translated strings are longer than the original English strings very often:

![test](https://user-images.githubusercontent.com/6333198/88486711-c379c880-cf90-11ea-8dbb-13f3baeaa597.png)

"Synchronize with Central Database" can be translated as "Синхронизировать с базой данных", because we see a more detailed description below (_the HardInfo central database_): minus 12 characters, it will be nicer. But width... Is it the final decision?

**Comment by lpereira** [comment]
Ah, yes, that looks bad. Will move where it was before. Thanks for the
screenshot!

**Comment by lpereira** [comment]
Also, I don't speak (or write) Russian, so I'll gladly accept patches
fixing the translation!
