### ISSUE TITLE
detect lang error

### ISSUE THREAD

**Issue by swrangsar** [lpereira/hardinfo#574]
while running make inside build/ in void linux-musl. i get the following error:

In file included from /usr/include/pango-1.0/pango/pango-utils.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:46,
                 from /usr/include/gtk-2.0/gdk/gdktypes.h:37,
                 from /usr/include/gtk-2.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from /home/swrangsar/src/hardinfo/modules/computer.c:20:
/home/swrangsar/src/hardinfo/modules/computer.c: In function 'scan_dev':
/home/swrangsar/src/hardinfo/modules/computer.c:321:27: error: expected identifier before '(' token
  321 |        if (detect_lang[i].stdout) {
      |                           ^~~~~~
make[2]: *** [CMakeFiles/computer.dir/build.make:83: CMakeFiles/computer.dir/modules/computer.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:181: CMakeFiles/computer.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**Comment by lpereira** [comment]
A fix has been pushed, can you please confirm?

**Comment by swrangsar** [comment]
[ 81%] Built target hardinfo
[ 82%] Building C object CMakeFiles/benchmark.dir/modules/benchmark.c.o
In file included from /home/swrangsar/repos/hardinfo/modules/benchmark.c:34:
/home/swrangsar/repos/hardinfo/modules/benchmark/bench_results.c:22:10: fatal error: json-glib/json-glib.h: No such file or directory
   22 | #include <json-glib/json-glib.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/benchmark.dir/build.make:82: CMakeFiles/benchmark.dir/modules/benchmark.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:261: CMakeFiles/benchmark.dir/all] Error 2
make: *** [Makefile:149: all] Error 2


have json-glib-devel installed already.

**Comment by lpereira** [comment]
I pushed a tentative fix for the json-glib issue, could you please give it a try again and report back if it works or not?

**Comment by swrangsar** [comment]
it works now. thanks
