### ISSUE TITLE
No "uninstall" make target

### ISSUE THREAD

**Issue by StatusCode404** [lpereira/hardinfo#616]
When trying out hardinfo from GitHub, there is no uninstall target for the make file.

```
$ sudo make uninstall
make: *** No rule to make target 'uninstall'.  Stop.
```
So now doing an uninstall is quite difficult as it would have to be done by reverse engineering all the copies from:
```
$ sudo make install
```

**Comment by lpereira** [comment]
`sudo rm < install_manifest.txt` from the build directory [should work instead](https://stackoverflow.com/a/44649542).

**Comment by StatusCode404** [comment]
Thanks!
