### ISSUE TITLE
Many benchmarks make no sense or are outright wrong

### ISSUE THREAD

**Issue by birdie-github** [lpereira/hardinfo#622]
I've used GCC 11.2, `-O3 -march=native` to build  hardinfo and sysbench. Perhaps some test results change from version to version. It would be great if `hardinfo` did **not** depend on external applications with variable test results.

Secondly: **144 cores across 18 NUMA nodes**? Desktop Ryzen 5000 CPUs are not NUMA compatible or capable.

My CPU cannot be slower than Ryzen 7 3700X. Also there's no way on Earth Ryzen 7 3700X can run at 5.554GHz:
![blowfish](https://user-images.githubusercontent.com/4958603/137493480-a69a30e8-4547-4253-abf4-d4fdd3daa9e1.png)

Likewise:
![blowfish-multicore](https://user-images.githubusercontent.com/4958603/137493482-0e9ea236-ac5b-47df-908d-8caeca753b0c.png)

A laptop CPU (4800H) which is **30 times** faster?
![sysbench-cpu](https://user-images.githubusercontent.com/4958603/137493483-747eb0d8-2203-4583-b9e4-50423e4cca67.png)

Likewise. An ultra low power Pentium N3700 which is many dozen times faster?
![sysbench-cpu-multi](https://user-images.githubusercontent.com/4958603/137493485-5cd55513-f297-4e85-aa6a-8f4c6b46cb12.png)

**Comment by lpereira** [comment]
Unfortunately these benchmark results are submitted by users when they choose the "Synchronize" option.  There's no manual validation of any sort, although the system tries to average results for the same machine ID (same CPU and clock speeds) when generating the benchmark result list for the day.  All the information that gets uploaded is information gathered by HardInfo from the system, including clock speeds, number of NUMA nodes, etc -- and there might be bugs in HardInfo where the information obtained does not match the actual system configuration; there's a reason we haven't had a release in over 10 years... the code for this tool isn't the greatest and maintaining it is kind of hard.

We try to build the benchmarks without optimizations to sort of even everything out, but we can't guarantee what's going to happen if people build HardInfo differently.

Take these results with a grain (or more) of salt.

**Comment by birdie-github** [comment]
You can perfectly do the following:

* Get rid of any external dependencies and use only built-in benchmarks
* Make benchmark results application version dependent
* Implement some server-side checking to avoid storing or presenting obviously wrong results

**Comment by lpereira** [comment]
What are obviously wrong results? It's not as simple as it sounds!

**Comment by lpereira** [comment]
In any case, the server is also open source and you can send a PR. It's in this repo, under the `server` branch.
