### ISSUE TITLE
Building from source in Fedora 35 results in GTK-2.0/1.0 GUI

### ISSUE THREAD

**Issue by maxreuben** [lpereira/hardinfo#641]
I built the app from source for Fedora 35, and it displays in gtk-1.0/2.0. I had used the app on fedora 34 and it used GTK-3. So I might be doing something wrong while building. How to make it switch to GTK3 on Fedora 35?
Here's what it looks like in Fedora 35(built from source):
![image](https://user-images.githubusercontent.com/28548154/150726817-056ad708-b8f5-4949-9943-faa3b7c9e629.png)

**Comment by maxreuben** [comment]
I tried using that flag to build it but the UI has not changed. Here's what I ran: 
1. `cmake .. -DHARDINFO_GTK3=ON`
2. `make`
When I launch it, i get the error `Gtk-Message: 22:27:20.558: Failed to load module "pk-gtk-module"`. Does that have anything to do with it?

**Comment by lpereira** [comment]
You have to install (with "sudo make install" or equivalent). If you have
installed HardInfo through a package manager, might be a good idea to
uninstall the package first.

**Comment by maxreuben** [comment]
I installed it using sudo make install and it worked. Thank you.
