### ISSUE TITLE
debian on RISCV64: hardinfo needs gtk2.0, which needs ... mono-runtime(?) ... which is not available ...

### ISSUE THREAD

**Issue by sanderjo** [lpereira/hardinfo#643]
I'm not sure if this is a hardinfo question, or a debian question, or just a PEBKAC

I'm running Debian bookworm/sid unstable on RISCV64. Via the standard repo's, hardinfo is avaible, but a 0.6-alpha from 2017.

So I tried to cmake / make hardinfo from git. It needs gtk2.0 (right?), but when I try to install that, it wants all kinds of mono stuff, which seems not available (because of RISCV64? https://packages.debian.org/search?suite=sid&arch=riscv64&searchon=names&keywords=mono-runtime says not available for riscv64)

Does hardinfo really need mono-runtime? Or is this a quirky gtk2.0 thing? If so, is there a workaround?
How was debian-repo able to compile hardinfo if it needs mono-runtime?
Or ... am I doing something wrong?

Tips how to proceed?

```
$ sudo apt install gtk2.0

...
libgtk2.0-bin is already the newest version (2.24.33-2).
libgtk2.0-bin set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 monodoc-base : Depends: mono-runtime (>= 3.0~) but it is not installable
                Depends: libmono-cecil-private-cil (>= 6.8.0.105) but it is not going to be installed
                Depends: libmono-cecil-private-cil (< 6.8.0.106) but it is not going to be installed
                Depends: libmono-corlib4.5-cil (>= 5.18.0.240) but it is not going to be installed
                Depends: libmono-sharpzip4.84-cil (>= 5.12.0.309) but it is not going to be installed
                Depends: libmono-system-xml-linq4.0-cil (>= 5.16.0.220) but it is not going to be installed
 monodoc-http : Depends: mono-xsp4 but it is not installable or
                         mono-apache-server4 but it is not installable or
                         mono-fastcgi-server4 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

FWIW:

the hardinfo provided by Debian's repos:

![image](https://user-images.githubusercontent.com/1273502/156881562-5b120395-92c1-4f31-b0b5-965085a6afb3.png)

**Comment by lpereira** [comment]
It shouldn't require mono! This is probably a packaging bug from the Debian side.

On Sat, Mar 5, 2022, at 2:34 AM, Sander wrote:
> 
> 
> I'm not sure if this is a hardinfo question, or a debian question, or just a PEBKAC
> 
> I'm running Debian bookworm/sid unstable on RISCV64. Via the standard repo's, hardinfo is avaible, but a 0.6-alpha from 2017.
> 
> So I tried to cmake / make hardinfo from git. It needs gtk2.0 (right?), but when I try to install that, it wants all kinds of mono stuff, which seems not available (because of RISCV64? https://packages.debian.org/search?suite=sid&arch=riscv64&searchon=names&keywords=mono-runtime says not available for riscv64)
> 
> 
> Does hardinfo really need mono-runtime? Or is this a quirky gtk2.0 thing? If so, is there a workaround?
> How was debian-repo able to compile hardinfo if it needs mono-runtime?
> Or ... am I doing something wrong?
> 
> Tips how to proceed?
> 
> `$ sudo apt install gtk2.0
> 
> ...
> libgtk2.0-bin is already the newest version (2.24.33-2).
> libgtk2.0-bin set to manually installed.
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  monodoc-base : Depends: mono-runtime (>= 3.0~) but it is not installable
>                 Depends: libmono-cecil-private-cil (>= 6.8.0.105) but it is not going to be installed
>                 Depends: libmono-cecil-private-cil (< 6.8.0.106) but it is not going to be installed
>                 Depends: libmono-corlib4.5-cil (>= 5.18.0.240) but it is not going to be installed
>                 Depends: libmono-sharpzip4.84-cil (>= 5.12.0.309) but it is not going to be installed
>                 Depends: libmono-system-xml-linq4.0-cil (>= 5.16.0.220) but it is not going to be installed
>  monodoc-http : Depends: mono-xsp4 but it is not installable or
>                          mono-apache-server4 but it is not installable or
>                          mono-fastcgi-server4 but it is not installable
> E: Unable to correct problems, you have held broken packages.
`

**Comment by sanderjo** [comment]
Hmmm ... maybe I was trying to install the wrong package? This seems to work:

`sudo apt install libgtk2.0-dev libjson-glib-dev
`

`cmake ..` was OK
`make` is now running ... fingers crossed

**Comment by sanderjo** [comment]
... and it works!

![image](https://user-images.githubusercontent.com/1273502/156927764-4dcf6804-3ab2-48ca-83ae-68755aa9b678.png)
