### ISSUE TITLE
impersonation of account or hijacked one .. caution

### ISSUE THREAD

**Issue by mckaygerhard** [lpereira/hardinfo#715]
i received a strange notificaiton of an older commit.. very rare and found this accoutn mostly similar to you @lpereira  

https://github.com/Babsak0

similar situation happened to me in the past in github.. seems M$ wants to fill gthub with many users to promote marketing i dont know.. i stored the page in archive org by the way

![image](https://github.com/user-attachments/assets/48dac33e-ba9a-49b9-97b5-73f6797b6c77)

**Comment by lpereira** [comment]
Thanks! Apparently the account has been suspended or removed.

**Comment by mckaygerhard** [comment]
do you know that this started to happens only since M$ owned gitshithub? @lpereira  ? puff

**Comment by lpereira** [comment]
> do you know that this started to happens only since M$ owned gitshithub? @lpereira ? puff

For the last time -- please stop with this kind of thing.
