### ISSUE TITLE
Properly license cmake/GNUInstallDirs.cmake

### ISSUE THREAD

**Issue by tsimonq2** [lpereira/hardinfo#76]
In the file `cmake/GNUInstallDirs.cmake`, it's in a gray area to include this in Debian at the moment because it states:
```
#=============================================================================
# Copyright 2011 Nikita Krupen'ko <krnekit@gmail.com>
# Copyright 2011 Kitware, Inc.
#
# Distributed under the OSI-approved BSD License (the "License");
# see accompanying file Copyright.txt for details.
#
# This software is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the License for more information.
#=============================================================================
# (To distribute this file outside of CMake, substitute the full
#  License text for the above reference.)
```

Yet, the license is nowhere to be found. `Copyright.txt` is not present, and there's only the short version of the license.

Could this please be fixed so this can be included in Debian properly?

**Comment by mapreri** [comment]
That file seems to come from an old cmake, and cmake is released under BSD-3-clause.
To comply with the license you could just embed a copy of the [BSD-3-clause](https://spdx.org/licenses/BSD-3-Clause) in the file, removing the reference to `Copyright.txt`.

OTOH, that's part of any cmake distribution afaik, so perhaps you can just rid of the file altogether?

**Comment by lpereira** [comment]
Indeed this file can be removed, as it's now part of CMake.

**Comment by mckaygerhard** [comment]
that file was include due some embebed linux does not have cmake recent.. and vendor cannot update due support concensus.. 

can be sustitued and change but please dont remove it!

**Comment by mckaygerhard** [comment]
and if are included in cmake ? i remenber that WAS TAKEN FROM CMAKE so ? debian revised the camke equivalent?

**Comment by mapreri** [comment]
> and if are included in cmake ? i remenber that WAS TAKEN FROM CMAKE so ? debian revised the camke equivalent?

Sorry but I cannot understand this sentence.

**Comment by mckaygerhard** [comment]
i take that piece of code from cmake of Debian.. i do myselft the commit here in the git... 

so now debian years passed and revised things that are not priority, theres many debian issues more importat that are never attended

**Comment by mckaygerhard** [comment]
i investigate and the piece of license can be removed.. pleae removeit as you prefer.. 

and remenber: i take that piece of code from cmake of Debian.. i do myselft the commit here in the git...
so now debian years passed and revised things that are not priority, theres many debian issues more importat that are never attended

**Comment by mapreri** [comment]
> so now debian years passed and revised things that are not priority, theres many debian issues more importat that are never attended

It's just that nobody actually ever checked with enough diligence.  *shrugs*


The fix is simple, either include somewhere (even inline) a copy of the BSD-3-clause license, or remove the file.  If you say the file can't be removed adding a BSD-3-clause license there isn't hard, I can even provide a PR for it.

**Comment by mckaygerhard** [comment]
that's i said, but i also take the oportunity to said that opinion about debian..

i'll make the pull request with your suggestions..

**Comment by mckaygerhard** [comment]
that's i said, but i also take the oportunity to said that opinion about debian..

i'll make the pull request with your suggestions.. or if your can made it please do now ..

**Comment by mapreri** [comment]
See, it's also noted on the file itself, for those not used to deal with licensing stuff:

https://github.com/lpereira/hardinfo/blob/736529e5dd123591a6ec63497d63d54f8ff80454/cmake/GNUInstallDirs.cmake#L42
```
# (To distribute this file outside of CMake, substitute the full
#  License text for the above reference.)
 ```

Please leave Debian outside of this thread, it has really nothing to do about this, apart from being the organization where I come from and uncovered this license violation.

**Comment by mckaygerhard** [comment]
thanks for the pull..
